apiVersion: v1
kind: Pod
metadata:
  name: tidb-loader-pod
  labels:
    app: tidb-loader
spec:
  restartPolicy: Never
  containers:
    - name: tidb-loader
      image: tidb-loader:latest
      imagePullPolicy: IfNotPresent
      env:
        - name: TIDB_PORT
          value: "4000"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: BATCH_SIZE
          value: "10"
        - name: TIDB_HOST
          valueFrom:
            secretKeyRef:
              name: tidb-credentials
              key: TIDB_HOST
        - name: TIDB_USER
          valueFrom:
            secretKeyRef:
              name: tidb-credentials
              key: TIDB_USER
        - name: TIDB_DATABASE
          valueFrom:
            secretKeyRef:
              name: tidb-credentials
              key: TIDB_DATABASE
        - name: TIDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tidb-credentials
              key: TIDB_PASSWORD
